# Generated by Django 3.0.2 on 2020-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InHouseProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('days', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
                ('participants', models.IntegerField()),
                ('language', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Senior Management', 'Senior Management'), ('Middle Management', 'Middle Management'), ('First Line Supervisory', 'First Line Supervisory'), ('Administration/Non-Supervisory', 'Administration/Non-Supervisory'), ('Mixed', 'Mixed')], max_length=200)),
                ('requirements', models.TextField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pobox', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
