# Generated by Django 3.0.2 on 2020-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurthor', '0002_authur_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='authur',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authur',
            name='facebook',
            field=models.CharField(default='www.facebook.com', max_length=150),
        ),
        migrations.AddField(
            model_name='authur',
            name='linkedin',
            field=models.CharField(default='www.facebook.com', max_length=150),
        ),
        migrations.AddField(
            model_name='authur',
            name='twitter',
            field=models.CharField(default='www.facebook.com', max_length=150),
        ),
    ]
