# Generated by Django 3.0.2 on 2020-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurthor', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='instructor_by_category',
            field=models.ManyToManyField(to='aurthor.Authur', verbose_name='Instructors for this Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='aurthor.Authur', verbose_name='Instructors for this Course'),
        ),
    ]
