# Generated by Django 3.0.2 on 2020-01-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_userpon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPon',
        ),
    ]
