# Generated by Django 3.0.2 on 2020-01-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_mycourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='user',
            new_name='user_id',
        ),
    ]
