# Generated by Django 3.0.2 on 2020-01-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200131_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_locality',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course_locality',
            name='date',
        ),
    ]
