# Generated by Django 3.0.2 on 2020-02-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurthor', '0002_authur_description'),
        ('courses', '0007_auto_20200131_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurthor.Authur'),
        ),
        migrations.AddField(
            model_name='course_locality',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='course_locality',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course_locality',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='course_locality',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurthor.Authur'),
        ),
    ]
