# Generated by Django 3.0.2 on 2020-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200202_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.ManyToManyField(null=True, to='courses.Course_Locality'),
        ),
    ]
