# Generated by Django 3.0.2 on 2020-02-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurthor', '0002_authur_description'),
        ('courses', '0010_auto_20200202_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_info',
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10000, null=True)),
                ('date', models.DateField(null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='courses.Course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurthor.Authur')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Language')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Location')),
            ],
            options={
                'verbose_name_plural': 'Course Localities',
            },
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='localty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInfo'),
        ),
        migrations.DeleteModel(
            name='Course_Locality',
        ),
    ]
