# Generated by Django 3.0.2 on 2020-02-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_mycourse_localty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinfo',
            options={'verbose_name_plural': 'Course Infomation'},
        ),
    ]
