# Generated by Django 3.0.2 on 2020-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200202_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
