# Generated by Django 3.0.2 on 2020-02-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_base_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
