# Generated by Django 3.0.2 on 2020-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_location_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='venue',
            field=models.CharField(default='Tom Luck, Avenue', max_length=100),
        ),
    ]
