# Generated by Django 3.0.2 on 2020-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_full_img',
            field=models.ImageField(default='/images/defualtbanner.PNG', upload_to='images/'),
        ),
    ]
