# Generated by Django 3.0.2 on 2020-02-11 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provison_users', '0009_auto_20200211_2349'),
        ('courses', '0022_auto_20200211_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourse',
            options={'verbose_name_plural': 'Registered Courses'},
        ),
        migrations.AddField(
            model_name='mycourse',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provison_users.Profile'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
