# Generated by Django 3.0.2 on 2020-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_mycourse_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='/category_icons/accounting-finance-training-courses.jpg', upload_to='category_icons/'),
        ),
    ]
