# Generated by Django 3.0.2 on 2020-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(default='/images/defaultcourseimg.jpg', upload_to='images/'),
        ),
    ]
