# Generated by Django 3.0.2 on 2020-01-21 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aurthor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('overview', models.TextField()),
                ('aurthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurthor.Authur')),
            ],
        ),
    ]
