# Generated by Django 3.0.2 on 2020-01-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='youtube_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
