# Generated by Django 3.0.2 on 2020-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_webinar_webinar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='webinar_profile_picture',
            field=models.ImageField(default='/images/test1.jpg', upload_to='webinar_icon/'),
        ),
    ]
