# Generated by Django 3.0.2 on 2020-01-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provison_users', '0002_auto_20200129_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Company'), (2, 'Individual')], default=2),
        ),
    ]
