# Generated by Django 3.0.2 on 2020-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provison_users', '0003_auto_20200129_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('COM', 'Company'), ('IND', 'Individual')], default='COM', max_length=3),
        ),
    ]
