# Generated by Django 3.0.2 on 2020-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provison_users', '0004_auto_20200129_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Individual', 'Individual')], default='Individual', max_length=10),
        ),
    ]
