# Generated by Django 3.0.2 on 2020-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provison_users', '0006_profile_signup_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=850, null=True),
        ),
    ]
